version: "3"

services:
                        
        idk-db:
                build: .
                container_name: idk-db
                ports:
                        - "3306:3306"
                volumes:
                        - ./data:/var/lib/mysql
        